name: heroku-jupyter
dependencies:
  # bind notebook version (compatibility to pgcontents)
  - notebook
  - ipywidgets = 6
  - requests
  # bind ipython version (compatibility to pgcontents)
  - ipython
  # bind tornado version (websocket problems)
  - tornado = 4.5
  # get dependencies for pgcontents
  - certifi
  - click
  - cryptography 
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip
  - pip:
    - ipysheet
    - pgcontents
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
