#!/usr/bin/env bash

pgcontents init -l $DATABASE_URL --no-prompt

jupyter contrib nbextension install --user
jupyter nbextensions_configurator enable --user

jupyter notebook \
	--no-browser --no-mathjax --ip=0.0.0.0 --port=5555 \
	$JUPYTER_NOTEBOOK_ARGS \
	notebooks
